### PR TITLE
Modify Promise check, Closes #20

### LINKED ISSUE #20: "Returns a Promise" check is incorrect
This library currently checks whether the callback returned a Promise by doing `returnVal instanceof Promise`, but this is incorrect; it only considers the global ES6 Promise implementation in the library's scope/realm, and not any other Promise implementations (including cross-realm Promises, non-global polyfills, and other Promises/A+ compliant Promise implementations such as Bluebird).

The correct check, as per the [Promises/A+ specification](https://promisesaplus.com/), would be more something like:

```js
returnVal != null && typeof returnVal.then === "function"
```

### PR DESCRIPTION
**Pull request by aulisius**
Based on discussion in #20 and googling around, I found this

https://stackoverflow.com/questions/27746304/how-do-i-tell-if-an-object-is-a-promise#27746324

It seems checking for the existence of a `then` on the prototype/instance is the most consistent solution.

I'm still thinking if there is a way to improve on this. 

@andyfleming @joepie91 Any thoughts?

### CODE REVIEW

**Comment by joepie91** [comment]
LGTM :)

**Comment by bobvanmanen** [comment]
Another use case for this is when `async-listener` is used. It overrides the global Promise into a WrappedPromise. If the interval function is an async function, the check will fail.

I wonder though, wouldn't it be better to just use this to ensure the returned value is always a Promise:

```
const returnVal = Promise.resolve(func(currentIteration, stop))
```

**Comment by andyfleming** [comment]
@bobvanmanen — I'm not sure about long-term, but initially I'm hesitant to make the assumption that non-promise values should just be resolved.

**Comment by andyfleming** [comment]
Thanks for your contribution @aulisius!

**Pull request merged**
